import type { AnalyticsSnapshot } from "./types";

export const SEED_ANALYTICS: AnalyticsSnapshot = {
  range: "30d",
  rangeLabel: "Last 30 days",
  generatedAt: new Date().toISOString(),
  fromLiveData: false,
  totals: { outreach: 12400, contacts: 1247, campaigns: 12 },
  kpis: [
    {
      id: "delivery",
      label: "Delivery success rate",
      value: "94.2%",
      change: "+2.4%",
      changeTone: "up",
      icon: "check_circle",
      tone: "sage",
    },
    {
      id: "response",
      label: "Avg. provider latency",
      value: "485ms",
      change: "-120ms",
      changeTone: "up",
      icon: "timer",
      tone: "bronze",
    },
    {
      id: "conversion",
      label: "Engagement rate",
      value: "24.9%",
      change: "+5.1%",
      changeTone: "up",
      icon: "trending_up",
      tone: "rose",
    },
    {
      id: "consent",
      label: "Consent health",
      value: "92/100",
      change: "Healthy",
      changeTone: "neutral",
      icon: "verified_user",
      tone: "sage",
    },
  ],
  trends: [
    { label: "Mon", connected: 420, failed: 28 },
    { label: "Tue", connected: 510, failed: 35 },
    { label: "Wed", connected: 480, failed: 42 },
    { label: "Thu", connected: 620, failed: 31 },
    { label: "Fri", connected: 590, failed: 38 },
    { label: "Sat", connected: 310, failed: 22 },
    { label: "Sun", connected: 280, failed: 18 },
  ],
  providers: [
    { id: "mock", name: "VoiceReach (mock)", count: 8060, percent: 65 },
    { id: "twilio", name: "Twilio", count: 3100, percent: 25 },
    { id: "other", name: "Other providers", count: 1240, percent: 10 },
  ],
  funnel: [
    { id: "outreach", label: "Total outreach", count: 100000, percent: 100 },
    { id: "connected", label: "Connected / delivered", count: 78420, percent: 78 },
    { id: "engagement", label: "Engagement", count: 32105, percent: 32 },
    { id: "converted", label: "High-intent leads", count: 14800, percent: 15 },
  ],
  campaigns: [
    {
      id: "seed-1",
      name: "Q4 Renewal Drive",
      subtitle: "Automated reach",
      volume: 42500,
      delivered: 37800,
      roi: "4.2x",
      roiTone: "good",
      status: "sent",
      deliveryRate: 89,
    },
    {
      id: "seed-2",
      name: "Feedback Loop A",
      subtitle: "Customer service",
      volume: 18200,
      delivered: 16400,
      roi: "3.8x",
      roiTone: "good",
      status: "sending",
      deliveryRate: 90,
    },
    {
      id: "seed-3",
      name: "Cold Prospecting",
      subtitle: "Sales velocity",
      volume: 64000,
      delivered: 42000,
      roi: "1.2x",
      roiTone: "warn",
      status: "draft",
      deliveryRate: 66,
    },
  ],
  channels: [
    { id: "vm", channel: "Ringless voicemail", icon: "voicemail", sent: 6200, rate: 42 },
    { id: "email", channel: "Email", icon: "mail", sent: 4100, rate: 28 },
    { id: "sms", channel: "SMS", icon: "sms", sent: 2800, rate: 19 },
    { id: "video", channel: "Avatar video", icon: "videocam", sent: 1600, rate: 11 },
  ],
};
