import type { ActivityLogEntry } from "./types";

/** Demo + engagement items shown when the account has little audit history */
export const SEED_ACTIVITY: ActivityLogEntry[] = [
  {
    id: "seed-eng-1",
    category: "engagement",
    icon: "voicemail",
    tone: "accent",
    title: "Marcus Chen listened to voicemail",
    body: "Listened to your ringless voicemail (87% completion).",
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/contacts",
  },
  {
    id: "seed-eng-2",
    category: "engagement",
    icon: "mail",
    tone: "success",
    title: "Sofia Alvarez clicked email",
    body: "Clicked your market update email — Pasadena luxury digest.",
    createdAt: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/contacts",
  },
  {
    id: "seed-eng-3",
    category: "engagement",
    icon: "sms",
    tone: "default",
    title: "James Whitfield replied via SMS",
    body: 'Replied: “Yes, let’s talk Thursday.”',
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/contacts",
  },
  {
    id: "seed-camp-1",
    category: "campaigns",
    icon: "rocket_launch",
    tone: "accent",
    title: "Summer Blast 2024 launched",
    body: "Campaign targeting new leads in California is now live.",
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/campaigns",
  },
  {
    id: "seed-comp-1",
    category: "compliance",
    icon: "gavel",
    tone: "error",
    title: "Compliance alert: re-consent needed",
    body: 'TCPA requirements changed for Florida. Update scripts for "Holiday Outreach".',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/settings",
    alert: true,
  },
  {
    id: "seed-auto-1",
    category: "automation",
    icon: "bolt",
    tone: "success",
    title: "Automation: lead sync complete",
    body: "Successfully synced 1,200 new contacts from Salesforce CRM integration.",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/automations",
  },
  {
    id: "seed-contact-1",
    category: "contacts",
    icon: "file_upload",
    tone: "default",
    title: "Contact batch uploaded",
    body: 'Batch "Retail_Contacts_Q3" (5,000 items) processed successfully.',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/contacts",
  },
  {
    id: "seed-camp-2",
    category: "campaigns",
    icon: "voicemail",
    tone: "success",
    title: "Voicemail delivery batch complete",
    body: "4,210 voicemails delivered with 89% success rate for Q4 Renewal.",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/campaigns",
  },
  {
    id: "seed-sys-1",
    category: "system",
    icon: "login",
    tone: "default",
    title: "User signed in",
    body: "Signed in from Chicago, IL (Chrome / Windows).",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    source: "seed",
    href: "/dashboard/settings",
  },
];
