export const clerkAppearance = {
  variables: {
    colorPrimary: "#1A1A1A",
    colorText: "#191c1e",
    colorTextSecondary: "#6B5E54",
    colorBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorInputText: "#191c1e",
    borderRadius: "9999px",
    fontFamily: "var(--font-inter), Inter, ui-sans-serif, system-ui, sans-serif",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none overflow-visible",
    card: "bg-transparent shadow-none border-0 p-0 gap-4 w-full overflow-visible",
    main: "gap-4 w-full",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    socialButtonsBlockButton:
      "h-11 w-full rounded-full border border-outline-variant/40 bg-white text-[14px] font-medium text-ink hover:bg-cream",
    socialButtonsBlockButtonText: "text-[14px] font-medium",
    socialButtons: "w-full",
    dividerRow: "my-2 w-full",
    dividerLine: "bg-outline-variant/40",
    dividerText: "text-taupe text-[12px]",
    form: "w-full gap-4",
    formFieldRow: "w-full",
    formFieldLabel: "text-[13px] font-medium text-ink",
    formFieldInput:
      "h-11 w-full rounded-full border border-outline-variant/40 bg-white px-4 text-[14px] focus:border-rose-gold/50 focus:ring-2 focus:ring-rose-gold/15",
    formButtonPrimary:
      "h-11 w-full rounded-full bg-ink text-[14px] font-semibold text-ivory shadow-sm hover:bg-ink/90",
    footer: "hidden !important",
    footerAction: "hidden !important",
    footerActionLink: "hidden !important",
    footerPages: "hidden !important",
    footerPagesLink: "hidden !important",
    badge: "hidden !important",
    identityPreviewEditButton: "text-rose-gold-deep",
    formFieldInputShowPasswordButton: "text-taupe",
    alert: "rounded-xl text-[13px]",
    otpCodeFieldInput: "rounded-xl border border-outline-variant/40",
    logoBox: "hidden",
    logoImage: "hidden",
  },
  layout: {
    socialButtonsPlacement: "top" as const,
    showOptionalFields: true,
  },
};
